version: "3.8"

services:
  backend:
    container_name: backend
    image: go-instagram-api
    networks:
      - go-instagram
    env_file:
      - .env.prod
    ports:
      - 5000:5000
    restart: always
