version: "3.8"

services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4.4.6
    networks:
      - go-net
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /data/db:/data/db

  backend:
    container_name: backend
    hostname: backend
    image: go-instagram-api
    networks:
      - go-net
    env_file:
      - .env
    ports:
      - 5000:5000

networks:
  go-net:
    name: go-net
    driver: bridge
